name: under_water
description: This application can clean up images taken in water.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  underwater_image_color_correction: ^1.0.4+1
  image_picker: ^0.8.6
  image: ^3.2.2
  image_gallery_saver: ^1.7.1
  google_mobile_ads: ^2.3.0
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
